### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by Naatan** [xcambar/github-better-filters#5] opened 2016-06-13 17:39 UTC
On Linux, I'm seeing this:

![image](https://cloud.githubusercontent.com/assets/278649/16017036/110f00dc-316c-11e6-8d1a-c5a8c0b80939.png)

**Comment by xcambar** [comment] 2016-06-14 08:06
What browser are you using?
Are you using the version from the store or did you build it yourself?

**Comment by SandNerd** [comment] 2016-06-17 14:01
Same thing and I installed it from the store. Below is my setup info.

Application Basics:
Name: Firefox
Version: 47.0
Build ID: 20160606114238
User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0
OS: Linux 4.2.0-38-generic x86-64
Multiprocess Windows: 0/2 (Disabled)
Safe Mode: false

Extension Info:
Name: Better Search For Github
Version: 1.1.2
Enabled: true
ID: @github-better-filters

**Comment by xcambar** [comment] 2016-06-19 10:26
Version 1.3.0 has been pushed. It should be available shortly in Chrome, but it should take a bit longer to hit FF (due to the review process).

Feel free to close the issue as soon as you've confirmed the fix.

**Comment by xcambar** [comment] 2016-06-21 08:24
1.3.0 has been published. @sahal2080 @Naatan did it fix your issues?

**Comment by SandNerd** [comment] 2016-06-21 15:02
Works like a charm on my end. Thanks :+1:

**Closed as completed** 2016-06-22 08:53 UTC
